[tool.mypy]
files=["tinyweb"]
python_version = "3.12" # micropython is ~3.5 but mypy doesn't support that

[[tool.mypy.overrides]]
module = ["ujson", "uos", "uerrno", "usocket"]
ignore_missing_imports = true


[tool.ruff]
include = [ "tinyweb/server.py" ]
