name: Run the tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run linters
        run: |
          pip3 install ruff==0.12.1 mypy==1.16.1
          mypy
          ruff check

      - name: Run tests
        run: |
          docker build . -t tinyweb

          # run with the local tinyweb mounted to the default search path
          # https://docs.micropython.org/en/latest/unix/quickref.html#envvar-MICROPYPATH
          docker run --rm \
            -v ./test:/srv/tinyweb/test \
            -v ./tinyweb:/root/.micropython/lib/tinyweb \
            tinyweb micropython /srv/tinyweb/test/test_server.py
